---

- name: Install Pulp consumer client and agent
  yum:
    name: "{{ item }}"
  with_items: pulp_consumer_pkgs

- name: Configure Pulp server
  template:
    src: consumer.conf.j2
    dest: /etc/pulp/consumer/consumer.conf
  notify:
    - Restart goferd service

- name: Make the goferd service running
  service:
    name: goferd
    state: running
